# @package _global_

model: hdemucs_slot_v2
batch_size: 16
dset :
  segment : 5.94

ema :
  epoch: [0.9,0.95]
  batch: [0.9995,0.9999]
  
epochs: 600
augment :
  repitch : 
    proba : 0
svd :
  penalty : 1e-5

continue_exist : false