# @package _global_
#slot 위치 변경
# config에서 기존 모델 1/4로 줄이고 depth도 1개 줄이고, 배치도 반, segment도 반으로 줄임
model: hdemucs_slot_tr
batch_size: 8
dset :
  segment : 2.97

ema :
  epoch: [0.9,0.95]
  batch: [0.9995,0.9999]
  
epochs: 600
augment :
  repitch : 
    proba : 0
svd :
  penalty : 1e-5

