# @package _global_

model: hdemucs_slot_ctr
batch_size: 4
dset :
  segment : 5.94

ema :
  epoch: [0.9,0.95]
  batch: [0.9995,0.9999]

epochs: 600
augment :
  repitch : 
    proba : 0
  remix :
    group_size : 1
svd :
  penalty : 1e-5

ctr : 
  positive : 1
  inter_negative :
    slot_count : 2
    batch_count : 4
  intra_negative : 
    slot_count : 2
    batch_count : 4

  